name: Overleaf Sync + XeLaTeX Build

on:
  schedule:
    - cron: '0 * * * *'   # Run hourly
  workflow_dispatch:

jobs:
  sync_compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    env:
      OUTPUT_PDF: main.pdf
      BUILD_DIR: overleaf_build

    steps:
      # ----------------------------
      # 1️⃣ Checkout repository
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # 2️⃣ Clone Overleaf project using Git token
      # ----------------------------
      - name: Clone Overleaf project (Git integration)
        run: |
          git clone https://git:${{ secrets.OVERLEAF_GIT_TOKEN }}@git.overleaf.com/${{ secrets.OVERLEAF_PROJECT_ID }}.git $BUILD_DIR
          cd $BUILD_DIR
          git checkout main || git checkout master || true

      # ----------------------------
      # 3️⃣ Compile with XeLaTeX
      # ----------------------------
      - name: Compile with XeLaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: xelatex
          working_directory: ${{ env.BUILD_DIR }}

      # ----------------------------
      # 4️⃣ Detect differences in repo
      # ----------------------------
      - name: Detect differences
        id: diffcheck
        run: |
          cd $BUILD_DIR
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # ----------------------------
      # 5️⃣ Upload compiled PDF
      # ----------------------------
      - name: Upload compiled PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: ${{ env.BUILD_DIR }}/${{ env.OUTPUT_PDF }}

      # ----------------------------
      # 6️⃣ Commit and push if changed
      # ----------------------------
      - name: Commit and push changes
        if: steps.diffcheck.outputs.changed == 'true'
        run: |
          cd $BUILD_DIR
          git config user.name "Overleaf Sync Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Overleaf Sync + XeLaTeX build [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]"
          git push origin main || git push origin master || true

      # ----------------------------
      # 7️⃣ Delete workflow run if no changes
      # ----------------------------
      - name: Delete workflow run if no change
        if: steps.diffcheck.outputs.changed == 'false'
        env:
          GH_PAT: ${{ secrets.ACTIONS_DELETE_PAT }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
        run: |
          if [ -n "$GH_PAT" ]; then
            echo "No changes — cleaning up run $RUN_ID"
            curl -sSL -X DELETE \
              -H "Authorization: Bearer $GH_PAT" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID"
          fi
