name: Overleaf Sync + XeLaTeX Build

on:
  schedule:
    - cron: '0 * * * *'   # Hourly
  workflow_dispatch:

jobs:
  sync_compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    env:
      OUTPUT_PDF: main.pdf
      BUILD_DIR: overleaf_build

    steps:
      # ----------------------------
      # 1️⃣ Checkout repository
      # ----------------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # ----------------------------
      # 2️⃣ Clone Overleaf project via Git Token
      # ----------------------------
      - name: Clone Overleaf repo (Git integration)
        run: |
          git clone https://git:${{ secrets.OVERLEAF_GIT_TOKEN }}@git.overleaf.com/${{ secrets.OVERLEAF_PROJECT_ID }} $BUILD_DIR

      # ----------------------------
      # 3️⃣ Compile with XeLaTeX
      # ----------------------------
      - name: Compile with XeLaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.BUILD_DIR }}/main.tex
          compiler: xelatex
          working_directory: ${{ env.BUILD_DIR }}

      # ----------------------------
      # 4️⃣ Detect differences
      # ----------------------------
      - name: Detect diff
        id: diffcheck
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # ----------------------------
      # 5️⃣ Upload compiled PDF
      # ----------------------------
      - name: Upload compiled PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: ${{ env.BUILD_DIR }}/${{ env.OUTPUT_PDF }}

      # ----------------------------
      # 6️⃣ Commit & push if changes exist
      # ----------------------------
      - name: Commit and push if changed
        if: steps.diffcheck.outputs.changed == 'true'
        env:
          GIT_AUTHOR_NAME: Overleaf Sync Bot
          GIT_AUTHOR_EMAIL: actions@github.com
        run: |
          cd $BUILD_DIR
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add .
          git commit -m "Overleaf Sync + XeLaTeX build [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]"
          git push origin master || git push origin main || true

      # ----------------------------
      # 7️⃣ Delete workflow run if unchanged
      # ----------------------------
      - name: Delete workflow run if no change
        if: steps.diffcheck.outputs.changed == 'false'
        env:
          GH_PAT: ${{ secrets.ACTIONS_DELETE_PAT }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
        run: |
          if [ -n "$GH_PAT" ]; then
            echo "No changes — cleaning up run $RUN_ID"
            curl -sSL -X DELETE \
              -H "Authorization: Bearer $GH_PAT" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID"
          fi
